### ISSUE TITLE
Protractor Issue

### ISSUE THREAD

**Issue by macdonaldr93** [firebase/angularfire-seed#86] opened 2015-05-21 02:36 UTC
I've been trying to get the protractor test to run for hours now and I can't get it to work. I keep getting this error: Failed at the angularfire-seed@1.0.0 protractor script 'protractor e2e-tests/protractor-conf.js'.

**Comment by katowulf** [comment] 2015-05-21 15:39
Hello! We will need considerably more context than this to be of any help here.

**Comment by macdonaldr93** [comment] 2015-05-21 16:21
Thank you for replying! I really appreciate it. I followed the steps in the README. I cloned the repository, and I ran npm install, etc. But when I attempt to use protractor I get this error.
![screen shot 2015-05-21 at 12 21 24 pm](https://cloud.githubusercontent.com/assets/5184848/7753517/f55b09ca-ffb3-11e4-9667-25cea9729e7d.png)

**Comment by katowulf** [comment] 2015-05-21 17:19
Looks like you can fix this by opening e2e-tests/protractor-conf.js and changing out the specs to this:

```
specs: [
    '*.js'
  ],
```

Not sure of the root cause, probably a change in how protractor considers the specs relative to CWD vs the .conf file.

**Comment by macdonaldr93** [comment] 2015-05-22 03:13
Wicked that seemed to work! Thank you for your help.

**Comment by katowulf** [comment] 2015-05-22 09:10
Going to keep this opened. Still not sure which versions are passing and which are failing. Will probably submit a fix for this to the seed.

**Comment by macdonaldr93** [comment] 2015-05-23 05:23
Okay sounds good. If you need more info, just let me know.



—
Ryan

Web Developer / Producer
www.rtmproductions.ca
(705) 561-2601

**Comment by katowulf** [comment] 2015-05-25 16:23
FIxed by [fbb0bc4fa92baa516180185dbcee6276a85d2323](https://github.com/firebase/angularfire-seed/commit/fbb0bc4fa92baa516180185dbcee6276a85d2323)

**Closed by katowulf** 2015-05-25 16:23 UTC
